/* ── Enums / Literal Unions ────────────────────────────── */

export type ClientType = 'b2b' | 'b2c'
export type ClientStatus = 'active' | 'inactive'
export type ObjectStatus = 'active' | 'inactive' | 'suspended'
export type PointType = 'trap' | 'bait_station' | 'feeder' | 'control_point' | 'uv_trap' | 'pheromone_trap'
export type PointStatus = 'active' | 'inactive' | 'triggered' | 'maintenance'
export type QrStatus = 'free' | 'bound' | 'deactivated'
export type VisitType = 'inspection' | 'treatment' | 'monitoring_check' | 'follow_up' | 'emergency'
export type VisitStatus = 'planned' | 'in_progress' | 'completed' | 'cancelled'
export type DocumentType = 'act' | 'monitoring_journal' | 'report' | 'service_plan' | 'inspection_report' | 'consumption_report' | 'recommendation' | 'contract'
export type DocumentStatus = 'draft' | 'ready' | 'published' | 'archived'
export type NotificationType = 'info' | 'warning' | 'critical' | 'task'
export type InspectionType = 'initial' | 'periodic' | 'audit'
export type InspectionStatus = 'planned' | 'in_progress' | 'completed' | 'cancelled'
export type UserRole = 'admin' | 'auditor' | 'master' | 'client'

/* ── Contact Person ─────────────────────────────────────── */

export interface ContactPerson {
  name: string
  role: string
  phone: string
  email: string
  comment: string
}

/* ── Zone ────────────────────────────────────────────────── */

export interface ObjectZone {
  name: string
  floor: string
  description: string
}

/* ── Core Entities ────────────────────────────────────── */

export interface Client {
  id: string
  companyName: string
  contactPerson: string
  phone: string
  email: string
  address: string
  type: ClientType
  status: ClientStatus
  notes: string
  companyId?: string
  contacts: ContactPerson[]
  edrpou: string
  inn: string
  legalAddress: string
  bankDetails: string
  createdAt: string
  updatedAt: string
}

export interface SiteObject {
  id: string
  clientId: string
  name: string
  address: string
  type: string
  floors: number
  contactOnSite: string
  contactPhone: string
  accessNotes: string
  floorPlanUrl: string
  status: ObjectStatus
  companyId?: string
  zones: ObjectZone[]
  assignedMasterId?: string
  assignedAuditorId?: string
  createdAt: string
  updatedAt: string
}

export interface MonitoringPoint {
  id: string
  objectId: string
  number: number
  tagId: string
  type: PointType
  zone: string
  floor: string
  positionX: number
  positionY: number
  status: PointStatus
  companyId?: string
  qrStatus: QrStatus
  nfcId?: string
  checkIntervalHours: number
  nextCheckDue: string | null
  installedAt: string
  lastCheckedAt: string | null
  notes: string
}

export interface Visit {
  id: string
  objectId: string
  clientId: string
  companyId?: string
  assignedTo: string
  scheduledAt: string
  completedAt: string | null
  type: VisitType
  status: VisitStatus
  notes: string
  pointsChecked: number
  pointsTotal: number
  createdAt: string
}

export interface CheckResult {
  id: string
  visitId: string
  pointId: string
  objectId: string
  companyId?: string
  activity: boolean
  activityLevel: number
  consumptionPercent: number | null
  consumptionGrams: number | null
  pestType: string
  photos: string[]
  correctiveAction: string
  equipmentStatus: string
  notes: string
  result: string
  remainingGrams: number | null
  refilledGrams: number | null
  checkedAt: string
  checkedBy: string
}

export interface Document {
  id: string
  objectId: string
  clientId: string
  visitId: string | null
  inspectionId: string | null
  companyId?: string
  type: DocumentType
  title: string
  status: DocumentStatus
  createdBy: string
  publishedToClient: boolean
  templateId?: string
  content?: string
  fileUrl?: string
  createdAt: string
  updatedAt: string
  publishedAt: string | null
}

export interface Notification {
  id: string
  type: NotificationType
  title: string
  message: string
  relatedEntity: string
  relatedId: string
  read: boolean
  userId?: string
  companyId?: string
  autoGenerated: boolean
  triggerEvent: string
  createdAt: string
}

export interface AuditLogEntry {
  id: string
  action: string
  entity: string
  entityId: string
  userId: string
  userName: string
  companyId?: string
  details: string
  createdAt: string
}

export interface ServicePlan {
  id: string
  objectId: string
  clientId: string
  companyId?: string
  title: string
  frequency: string
  pestTypes: string[]
  zones: string[]
  startDate: string
  endDate: string | null
  status: 'active' | 'paused' | 'completed'
  accessConditions: string
  workTypes: string[]
  notes: string
  createdAt: string
}

export interface Inspection {
  id: string
  objectId: string
  clientId: string
  companyId?: string
  type: InspectionType
  status: InspectionStatus
  scheduledAt: string
  completedAt: string | null
  assignedTo: string
  checklist: { question: string; answer: string }[]
  findings: string[]
  riskZones: string[]
  recommendations: string[]
  photos: string[]
  notes: string
  actDocumentId?: string
  createdAt: string
  updatedAt: string
}

export interface HeatmapPoint {
  pointId: string
  x: number
  y: number
  score: number
  zone: string
  floor: string
  checks: number
}

/* ── Helpers ──────────────────────────────────────────── */

export const POINT_TYPE_LABELS: Record<string, string> = {
  trap: 'Пастка',
  bait_station: 'Приманкова станція',
  feeder: 'Годівниця',
  control_point: 'Контрольна точка',
  uv_trap: 'УФ-пастка',
  pheromone_trap: 'Феромонна пастка',
}

export const VISIT_TYPE_LABELS: Record<string, string> = {
  inspection: 'Обстеження',
  treatment: 'Обробка',
  monitoring_check: 'Перевірка точок',
  follow_up: 'Контрольний виїзд',
  emergency: 'Екстрений виїзд',
}

export const VISIT_STATUS_LABELS: Record<string, string> = {
  planned: 'Заплановано',
  in_progress: 'В роботі',
  completed: 'Завершено',
  cancelled: 'Скасовано',
}

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  act: 'Акт',
  monitoring_journal: 'Журнал моніторингу',
  report: 'Звіт',
  service_plan: 'План обслуговування',
  inspection_report: 'Акт обстеження',
  consumption_report: 'Звіт витрати',
  recommendation: 'Рекомендації',
  contract: 'Договір',
}

export const DOCUMENT_STATUS_LABELS: Record<string, string> = {
  draft: 'Чернетка',
  ready: 'Готовий',
  published: 'Опублікований',
  archived: 'Архів',
}

export const QR_STATUS_LABELS: Record<QrStatus, string> = {
  free: 'Вільний',
  bound: "Прив'язаний",
  deactivated: 'Деактивований',
}

export const INSPECTION_TYPE_LABELS: Record<InspectionType, string> = {
  initial: 'Первинне',
  periodic: 'Періодичне',
  audit: 'Аудит',
}

export const INSPECTION_STATUS_LABELS: Record<InspectionStatus, string> = {
  planned: 'Заплановано',
  in_progress: 'В роботі',
  completed: 'Завершено',
  cancelled: 'Скасовано',
}
