import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Notification } from './notification.entity';

@Injectable()
export class NotificationsService {
  constructor(
    @InjectRepository(Notification) private repo: Repository<Notification>,
  ) {}

  findAll() {
    return this.repo.find({ order: { createdAt: 'DESC' }, take: 100 });
  }

  findUnread() {
    return this.repo.find({ where: { read: false }, order: { createdAt: 'DESC' } });
  }

  create(data: Partial<Notification>) {
    const notification = this.repo.create(data);
    return this.repo.save(notification);
  }

  async createAuto(
    type: string,
    title: string,
    message: string,
    relatedEntity: string,
    relatedId: string,
    triggerEvent: string,
    userId?: string,
  ) {
    return this.create({
      type,
      title,
      message,
      relatedEntity,
      relatedId,
      autoGenerated: true,
      triggerEvent,
      userId,
    });
  }

  async markRead(id: string) {
    await this.repo.update(id, { read: true });
    return this.repo.findOne({ where: { id } });
  }

  async markAllRead() {
    await this.repo.update({ read: false }, { read: true });
    return { success: true };
  }
}
